import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useStoreState } from 'easy-peasy';
import Todos from '../components/todos';
import Link from 'next/link'
//import todosModel from '../store/todos';

export default function About() {
  const todos = useStoreState(state => state.todos.items.length);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-5 border-b border-gray-200">
      <div className="-ml-2 -mt-2 flex flex-wrap items-baseline">
        <h3 className="ml-2 mt-2 text-lg leading-6 font-medium text-gray-900">Todos Length = {todos}</h3>
        <p className="ml-2 mt-1 text-sm text-gray-500 truncate">in Engineering</p>
      </div>
      </div>

      <main>


        <Todos/>
      </main>
    </div>
  )
}
