import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useStoreState } from 'easy-peasy';
import PageHeading from '../components/PageHeading';
import Link from 'next/link'
//import todosModel from '../store/todos';

export default function Home() {
  const todos = useStoreState(state => state.todos.items.length);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeading/>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Todos Length = {todos}
        </h1>

        <p className={styles.description}>
          Home
        </p>


      </main>
    </div>
  )
}
